### ISSUE TITLE
Installation fails, no measurements are send, removing target freezes browser

### ISSUE THREAD

**Issue by niirvana-git** [balda/ruuvitag-discovery#32] opened 2020-12-12 18:00 UTC
Add-on seems to be very buggy at the moment. I'm trying to use the latest version, but with no success.

First, already installation of the add-on fails with this error below (I'm using NGINGX): 
`<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

However, after rebooting home assistant, add-on is available.  UI seems to work, but after setting up everything correctly, no measurements are found in home assistant. RuuviTag can be found under devices and also all selected entities, but there are no values/measurements.

Also, add-on crashes, if I try to remove any targets. Browser window just halts and I have to reboot home assistant.

-----------------------------------------------------------
 Add-on: RuuviTag Discovery
 Web interface to Discover RuuviTag Environmental Sensors and save measures to Home Assistant, MQTT, InfluxDB and Graphite
-----------------------------------------------------------
 Add-on version: 0.2.2
 You are running the latest version of this add-on.
 System: HassOS 4.17  (armv7 / raspberrypi4)
 Home Assistant Core: 0.118.5
 Home Assistant Supervisor: 2020.12.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------

**Comment by balda** [comment] 2020-12-12 21:53
WebSocket (over http) is used to update tags measure in real time. If release `0.2.3` don't fix your problems, nginx configuration with websockets can be a lead.

Do you use the NGINX Home Assistant SSL proxy? Or another nginx addon?

**Comment by niirvana-git** [comment] 2020-12-13 17:35
Thanks for the comments! I'll try that new version. I was also thinking that NGINX might have something to do with the issue. I'm using NGINS Proxy Manager and actually also client certificates.

**Comment by niirvana-git** [comment] 2020-12-14 16:23
Unfortunately, it still isn't working for me. I enabled all the logging. Here's a snippet from the log. It shouldn't contain anything sensitive. Any ideas what's wrong? NGINX Proxy Manager should not affect on internal traffic.

cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
> ruuvitag-discovery@0.2.3 start /app
> NODE_ENV=production node index.js
[2020-12-14T16:16:56.868Z] Start RuuviTag Discovery - v0.2.3
[2020-12-14T16:16:56.953Z] Start measures sampling every 10 seconds
[2020-12-14T16:16:57.089Z] [DEBUG] [HA MQTT] Search device measures to present for tag {"id":1,"selected":true,"measures":{"temperature":{"label":"Temperature","field":"temperature"},"humidity":{"label":"Humidity","field":"humidity"},"pressure":{"label":"Pressure","field":"pressure"},"battery":{"label":"Battery","field":"battery"},"battery_level":{"label":"Battery Level","field":"battery_level"},"rssi":{"label":"RSSI","field":"rssi"},"absolute_humidity":{"label":"Absolute Humidity","field":"absolute_humidity"}},"name":"RuuviTag ea51b710644c","field":"ruuvitag_ea51b710644c"}
[2020-12-14T16:16:57.090Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/dataFormat
[2020-12-14T16:16:57.092Z] [DEBUG] [HA MQTT] Present device measure: {"stat_t":"homeassistant/sensor/1/temperature/state","json_attr_t":"homeassistant/sensor/1/temperature/attributes","name":"RuuviTag ea51b710644c Temperature","unit_of_meas":"°C","dev_cla":"temperature","uniq_id":"ruuvitag_1_temperature","device":{"ids":"ruuvitag-1","mf":"Ruuvi Innovations Ltd","mdl":"RuuviTag","name":"RuuviTag ea51b710644c"}}
[2020-12-14T16:16:57.093Z] [DEBUG] [HA MQTT] Present device measure: {"stat_t":"homeassistant/sensor/1/humidity/state","json_attr_t":"homeassistant/sensor/1/humidity/attributes","name":"RuuviTag ea51b710644c Humidity","unit_of_meas":"%","dev_cla":"humidity","uniq_id":"ruuvitag_1_humidity","device":{"ids":"ruuvitag-1","mf":"Ruuvi Innovations Ltd","mdl":"RuuviTag","name":"RuuviTag ea51b710644c"}}
[2020-12-14T16:16:57.094Z] [DEBUG] [HA MQTT] Present device measure: {"stat_t":"homeassistant/sensor/1/pressure/state","json_attr_t":"homeassistant/sensor/1/pressure/attributes","name":"RuuviTag ea51b710644c Pressure","unit_of_meas":"hPa","dev_cla":"pressure","uniq_id":"ruuvitag_1_pressure","device":{"ids":"ruuvitag-1","mf":"Ruuvi Innovations Ltd","mdl":"RuuviTag","name":"RuuviTag ea51b710644c"}}
[2020-12-14T16:16:57.095Z] [DEBUG] [HA MQTT] Present device measure: {"stat_t":"homeassistant/sensor/1/battery/state","json_attr_t":"homeassistant/sensor/1/battery/attributes","name":"RuuviTag ea51b710644c Battery","unit_of_meas":"mV","uniq_id":"ruuvitag_1_battery","icon":"mdi:battery-bluetooth-variant","device":{"ids":"ruuvitag-1","mf":"Ruuvi Innovations Ltd","mdl":"RuuviTag","name":"RuuviTag ea51b710644c"}}
[2020-12-14T16:16:57.096Z] [DEBUG] [HA MQTT] Present device measure: {"stat_t":"homeassistant/sensor/1/battery_level/state","json_attr_t":"homeassistant/sensor/1/battery_level/attributes","name":"RuuviTag ea51b710644c Battery Level","unit_of_meas":"%","dev_cla":"battery","uniq_id":"ruuvitag_1_battery_level","device":{"ids":"ruuvitag-1","mf":"Ruuvi Innovations Ltd","mdl":"RuuviTag","name":"RuuviTag ea51b710644c"}}
[2020-12-14T16:16:57.096Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/accelerationX
[2020-12-14T16:16:57.097Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/accelerationY
[2020-12-14T16:16:57.097Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/accelerationZ
[2020-12-14T16:16:57.098Z] [DEBUG] [HA MQTT] Present device measure: {"stat_t":"homeassistant/sensor/1/rssi/state","json_attr_t":"homeassistant/sensor/1/rssi/attributes","name":"RuuviTag ea51b710644c RSSI","unit_of_meas":"dBm","dev_cla":"signal_strength","uniq_id":"ruuvitag_1_rssi","device":{"ids":"ruuvitag-1","mf":"Ruuvi Innovations Ltd","mdl":"RuuviTag","name":"RuuviTag ea51b710644c"}}
[2020-12-14T16:16:57.098Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/acceleration
[2020-12-14T16:16:57.099Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/equilibrium_vapor_pressure
[2020-12-14T16:16:57.099Z] [DEBUG] [HA MQTT] Present device measure: {"stat_t":"homeassistant/sensor/1/absolute_humidity/state","json_attr_t":"homeassistant/sensor/1/absolute_humidity/attributes","name":"RuuviTag ea51b710644c Absolute Humidity","unit_of_meas":"g/m3","uniq_id":"ruuvitag_1_absolute_humidity","icon":"mdi:water","device":{"ids":"ruuvitag-1","mf":"Ruuvi Innovations Ltd","mdl":"RuuviTag","name":"RuuviTag ea51b710644c"}}
[2020-12-14T16:16:57.100Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/air_density
[2020-12-14T16:16:57.100Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/dew_point
[2020-12-14T16:16:57.101Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/vapor_pressure_deficit
[2020-12-14T16:16:57.101Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/txPower
[2020-12-14T16:16:57.102Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/movementCounter
[2020-12-14T16:16:57.102Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/measurementSequenceNumber
[2020-12-14T16:16:57.103Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/samples
[2020-12-14T16:16:57.103Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/frequency
[2020-12-14T16:16:57.104Z] [DEBUG] [HA MQTT] Unpresent device measure homeassistant/sensor/1/period
[2020-12-14T16:16:57.105Z] Start web server on port 8099
[2020-12-14T16:16:57.138Z] Connected to MQTT "HA"
[2020-12-14T16:17:07.171Z] Discover RuuviTag ea51b710644c
[2020-12-14T16:17:07.181Z] [TAGS] Got data from RuuviTag ea51b710644c: {"dataFormat":5,"rssi":-63,"temperature":22.66,"humidity":23.57,"pressure":100923,"accelerationX":-16,"accelerationY":-20,"accelerationZ":1052,"battery":3157,"txPower":4,"movementCounter":134,"measurementSequenceNumber":30438,"mac":"EA:51:B7:10:64:4C","ts":1607962627176,"battery_level":100,"equilibrium_vapor_pressure":2751.2,"dew_point":0.82,"air_density":1.19,"absolute_humidity":4.75,"acceleration":1088,"vapor_pressure_deficit":20.71,"id":"ea51b710644c"}

**Comment by niirvana-git** [comment] 2020-12-15 18:46
Some more debugging done. RuuviTag Discovery sends MQTT messages and HA receives them successfully. Temperature as an example below.

`homeassistant/sensor/ea51b710644c/temperature/attributes 20.36:
{
    "RuuviTag": "ea51b710644c",
    "Measure": "Temperature",
    "Unit": "°C"
}`

`homeassistant/sensor/ea51b710644c/temperature/state 20.36:
22.31
`

However, devices and entities auto-discovered are somehow incorrect or don't get any values. For instance, entity id for temperature is "sensor.ruuvitag_ea51b710644c_temperature". It doesn't get any values. From device and MQTT info I can see that subscribed topic is different than above. There's that "sensor/1" and not that actual RuuviTag id. Any pointers how to fix it?

'RuuviTag ea51b710644c Temperature' (sensor.ruuvitag_ea51b710644c_temperature)
MQTT discovery data:
Topic: homeassistant/sensor/1/temperature/config
Payload
Subscribed topics:
**homeassistant/sensor/1/temperature/attributes**
0 last received messages
**homeassistant/sensor/1/temperature/state**
0 last received messages

**Comment by niirvana-git** [comment] 2020-12-15 19:08
Actually it seems to work, if I manually edit RuuviTag Discover config and change that id in the config to "ea51b710644c". Then values are visible in home assistant. Is it a bug in your code @balda?

**Comment by balda** [comment] 2020-12-15 19:40
You're right, the `"id"` value in `"tags": { "ea51b710644c": { "id": ... ` should be the same as the object key (`ea51b710644c` in your example).
I'll double check my code to see if (or where) I update the id (maybe the bug was just in an older release and you saved at the wrong moment :/ ).

I have planned to check the validity of the config and to rewrite good data / format if needed: I'll put this now on the top of my todo list.

Thank you for taking the time to review the logs and successfully find the cause of the bug :)

**Comment by niirvana-git** [comment] 2020-12-16 17:56
> Thank you for taking the time to review the logs and successfully find the cause of the bug :)

No problem! Good that I could help in finding the bug :-) Add-on seems to work fine now. Thanks for it!

By the way, I removed and reinstalled the add-on quite many times and also before installing the latest version, so it's strange why id wasn't the correct one. Removing probably deletes configs etc.

**Comment by balda** [comment] 2020-12-19 11:29
As the add-on seems to work fine, I close the issue.

Re-open it (or another) if problems come back.

**Closed by balda** 2020-12-19 11:29 UTC
